spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ms-customer
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yml
    enabled: true
server:
  port: 8090
